Algoritmo "conteAte10"
// Disciplina  : [Algoritmo]
// Professor   : Gustavo Guanabara
// Descrição   : Contador
// Autor(a)    : Marcelo Soares Moura
// Data atual  : 01/08/2023
Var
// Seção de Declarações das variáveis
   contador : Inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   contador <- 0
   Enquanto (contador <= 10) faca
      EscrevaL (contador)
      contador <- contador + 1
   FimEnquanto
   EscrevaL ("Terminei de contar!")


Fimalgoritmo