Algoritmo "Contador"
// Disciplina   : [Algoritmo]
// Professor   : Gustavo Guanabara
// Descrição   : Contador
// Autor(a)    : Marcelo Soares Moura
// Data atual  : 18/07/2023
Var
// Seção de Declarações das variáveis 
   contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   contador <- 0
   Enquanto (contador <= 10) faca
        Escreval (contador)
        contador <- contador + 1
   FimEnquanto
   Escreval ("Terminei de contar")

Fimalgoritmo