Algoritmo "dollar"
// Disciplina  : Exercicios de Algoritmo Resolvidos
// Professor   : Gustavo Guanabara
// Descrição   : Dollar
// Autor(a)    : Marcelo Soares Moura
// Data atual  : 27/06/2023
Var
// Seção de Declarações das variáveis 
   reais, dollar: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Quantos reais voce tem? ")
   Leia(reais)
   dollar <- reais / 5
   Escreva("Voce tem ", dollar, " dolares")


Fimalgoritmo