Algoritmo "temperatura"
// Disciplina  : Exercicios de Algoritmo Resolvidos
// Professor   : Gustavo Guanabara
// Descrição   : Temperatura
// Autor(a)    : Marcelo Soares Moura
// Data atual  : 27/06/2023
Var
// Seção de Declarações das variáveis 
   F, C: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Qual e a temperatura aqui? ")
   Leia(F)
   C <- (F - 32) / 1.8
   Escreva("No Brasil seria ", C:4:1, " graus celsius")


Fimalgoritmo